### ISSUE TITLE
尊敬的作者您好

### ISSUE THREAD

**Issue by renjiu13** [wdvipa/sspsign#12]
## 开始执行... 2023-12-28 11:33:24

您没有输入任何信息

## 执行结束...   耗时 10 秒　

这种脚本是否失效了呢？

**Comment by wdvipa** [comment]
> ## 开始执行...2023-12-28 11:33:24
> 您没有输入任何信息
> 
> ## 执行结束...耗时 10 秒
> 这种脚本是否失效了呢？

请仔细检查你是否有添加青龙变量或名字是否正确
