### ISSUE TITLE
请问有教程吗？

### ISSUE THREAD

**Issue by renjiu13** [wdvipa/sspsign#3]
emm,太笨了，ssp.py。里面的信息怎么填，填了之后实在懵，青龙需要设置别的了吗？

**Comment by wdvipa** [comment]
emmm，py里面不需要填，青龙加变量就行
看看，星期六我b站发个教程

**Comment by renjiu13** [comment]
非常感谢您的回复，可是我没有找到您的B站上的信息，无法关注您，你可以告诉我您的UID吗？

**Comment by wdvipa** [comment]
> 非常感谢您的回复，可是我没有找到您的B站上的信息，无法关注您，你可以告诉我您的UID吗？

搜索：征途wd即可,我发了会更新文档的

**Comment by wdvipa** [comment]
> 非常感谢您的回复，可是我没有找到您的B站上的信息，无法关注您，你可以告诉我您的UID吗？

已更新，视频：https://www.bilibili.com/video/BV1bv411F7HL/

**Comment by renjiu13** [comment]
非常感谢
